//ARTICLE
export const ARTICLE_DATA = 'ARTICLE_DATA';
export const ARTICLE_DATA_ERROR = 'ARTICLE_DATA_ERROR';
export const RESET_ARTICLE = 'RESET_ARTICLE';
export const RESET_DATA_ARTICLE = 'RESET_DATA_ARTICLE';

//HOME
export const HOME_DATA = 'HOME_DATA';
export const HOME_DATA_ERROR = 'HOME_DATA_ERROR';
export const RESET_HOME = 'RESET_HOME';

//MENU
export const MENU_DATA = 'MENU_DATA';
export const MENU_DATA_2 = 'MENU_DATA_2';
export const MENU_DATA_ERROR = 'MENU_DATA_ERROR';
export const RESET_MENU = 'RESET_MENU';

//REGISTER
export const REGISTER_DATA = 'REGISTER_DATA';
export const REGISTER_DATA_ERROR = 'REGISTER_DATA_ERROR';
export const RESET_REGISTER = 'RESET_REGISTER';

//LOGIN
export const LOGIN_DATA = 'LOGIN_DATA';
export const LOGIN_DATA_ERROR = 'LOGIN_DATA_ERROR';
export const RESET_LOGIN = 'RESET_LOGIN';

//LOGOUT
export const LOGOUT = 'LOGOUT';
